apiVersion: garden.io/v0
kind: Project
name: thx-sample-project
variables:
  skipBuild: false # skip build dependency in the templates
  gardenProjectName: thx
  dockerRepo: dockerRepoURLs
  baseImageJava8: eclipse-temurin:8u345-b01-jre-ubuntu23
  baseImageJava11: distroless-os-images:debian11-java11.0.18
  namespace: thx
  projectname: sharedServices
  withPlan: false # requires plan to deploy services
  deploymentRegistry:
    hostname: docker-registry-hostname
    namespace: namespace

environments:
  - name: dev
    variables:
      springProfiles: gcp,gcp-dev

providers:
  - name: jib # <----
    environments: ["dev"]
  - name: local-kubernetes
    environments: ["dev"]
  - name: pulumi
    environments: ["dev"]
    # The version of pulumi to use. Set to `null` to use whichever version of `pulumi` is on your PATH.
    version: 3.64.0
    orgName: org_name
