
################ ERROR ############
### Below placeholder are not working as reported Could not find key parent. 
### Available keys: actions, command, datetime, environment, git, inputs, local, modules, project, providers, runtime, secrets, this, var and variables

###${var.pulumiProjectName}:app-name: ${ parent.name }
###${var.pulumiProjectName}:app-name-suffix:
###${var.pulumiProjectName}:image-name: ${parent.name}

##################

${var.pulumiProjectName}:app-name: spring-boot

${var.pulumiProjectName}:image-name: spring-boot-image
${var.pulumiProjectName}:app-version: ${modules["spring-boot-image"].version}
